# Generated by Django 3.0.7 on 2020-06-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pathologist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('specialty', models.CharField(default='', max_length=200)),
                ('location', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
